site_name: Gigaflow vSwitch (GvS)
site_author: Annus Zulfiqar
copyright: Copyright &copy; 2025 NextGArch Lab, University of Michigan

nav:
  - Home: 
    - home/home.md
    - Publications: home/publications.md
  - Getting Started: 
    - Overview: getting-started/overview.md
    - Setup and Installation: getting-started/installation.md
    - Demo: getting-started/demo.md
  - Gigaflow Deep Dive:
    - Gigaflow Architecture: deepdive/architecture.md
    - Gigaflow Fast Path: deepdive/fast-path.md
    - Gigaflow Slow Path: deepdive/slow-path.md
  - User Guide:
    - Project Configuration: userguide/configuration.md
    - Usage: userguide/usage.md
    - Examples: userguide/examples.md
  - About: 
    - Release Notes: about/release-notes.md
    - Team: about/about.md

theme: 
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  # favicon: material/format-line-style
  icon:
    logo: material/alpha-g-circle

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/solid/file-pdf
      link: https://annuszulfiqar2021.github.io/papers/gigaflow-asplos2025.pdf
    - icon: fontawesome/brands/github
      link: https://github.com/gigaflow-vswitch
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/annuszulfiqar/
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/mshahbaz/mshahbaz.gitlab.io/-/wikis/home

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
